{
	global: {
	  	print: 0,rule: 1,showfile: 0,interval: 15,target: "file_global",
	  	buffer: {engine: 2,target: "redis_buffer"}
	},
	store: {
		redis: {
			redis_buffer: {addr: "192.168.33.70:6379",db: 0,poolsize: 10}
		},
		file: {
			file_global: {
		      filepath: "logs",
		      filename: "{{.Year}}{{.Month}}{{.Day}}.log",
		      filesize: 2048,
		      item: {
        		tmpl: '{{.ID}} {{.Time}} {{.Level}} {{.Tag}} "{{.FileName}} {{.FileFuncName}} {{.FileLine}}" {{.Message}}',
		        time: "{{.Year}}-{{.Month}}-{{.Day}} {{.Hour}}:{{.Minute}}:{{.Second}}.{{.MilliSecond}}"
		      }
			}
		}
	}
}