{
	console: {
		level: 1,
		item: {
			tmpl: "[{{.ID}} {{.Time}} {{.Level}} {{.Tag}}] {{.Message}}",
			time: "{{.Hour}}:{{.Minute}}"
		}
	},
	global: {
	  	print: 1,rule: 1,showfile: 1,caller: 5,interval: 1,target: "file_global",
	  	buffer: {engine: 1}
	},
	store: {
		file: {
			file_global: {
		      filepath: "logs",
		      filename: "{{.Year}}{{.Month}}{{.Day}}.log",
		      filesize: 2048,
		      item: {
        		tmpl: '{{.ID}} {{.Time}} {{.Level}} {{.Tag}} "{{.ShortName}} {{.FileLine}} {{.FileFuncName}}" {{.Message}}',
		        time: "{{.Year}}-{{.Month}}-{{.Day}} {{.Hour}}:{{.Minute}}:{{.Second}}.{{.MilliSecond}}"
		      }
			}
		}
	}
}